image_width: 600
image_height: 600

fov: 40
camera_position: [278, 278, 800]
camera_look_at: [278, 278, 0]
focus_dist: 10.0
defocus_angle: 0.0

samples_per_pixel: 200
max_depth: 50

gamma: 0.5
scene: cornell_box
