image_width: 800
image_height: 800

fov: 40
camera_position: [478, 278, -600]
camera_look_at: [278, 278, 0]
focus_dist: 10.0
defocus_angle: 0

samples_per_pixel: 10000
max_depth: 40

gamma: 0.5
scene: final

